### ISSUE TITLE
Is project still active?

### ISSUE THREAD

**Issue by maoo** [finos/exodus#6]
Hi @ChristianLeigh !

I see that there haven't been updates on this repo since a long time; is it still used/relevant, or shall we archive it?

Thanks in advance!

**Comment by ChristianLeigh** [comment]
Yes. This is still active. Regards. Christian. Sent from my iPhone, please excuse brevity, spelling, and punctuation errors. On 15 Mar 2023, at 19:40, Maurizio Pillitu ***@***.***> wrote:﻿
Hi @ChristianLeigh !
I see that there haven't been updates on this repo since a long time; is it still used/relevant, or shall we archive it?
Thanks in advance!

**Comment by maoo** [comment]
Thank you @ChristianLeigh

**Comment by ChristianLeigh** [comment]
It’s being accessed by people I know, but development work is probably at an end.

**Comment by maoo** [comment]
Thanks for the response @ChristianLeigh 

> It’s being accessed by people I know, but development work is probably at an end.

If that's the case, I'd suggest to archive the project, as it would still allow users to consume code and releases, yet it will warn them that code is not maintained. If you don't have any objection, we can proceed with archiviation.

**Comment by ChristianLeigh** [comment]
Ok.
